spring:
  application:
    name: ecomconfigserver
  cloud:
    config:
      server:
        git:
          #          uri: https://github.com/navsingh3211/cxp-config
          uri: file:/usr/local/src/myWork/MicroServices/cxp-config
    #          username: ${GIT_USER}
    #          password: ${GIT_TOKEN}


server:
  port: 8889
